[book]
title = "Notas de Filosofía [Philosophy Books Notes]"
authors = ["Carlos Andrés Mata Calderón"]
src = "notas"
language = "es"

[output.html.print]
enable = true     # include support for printable output
page-break = true # insert page-break after chapter

[output.html]
mathjax-support = true
